"""auto_generated_migration

Revision ID: 609d9d2ed8cc
Revises: 4c343cfa2628
Create Date: 2025-02-18 12:52:58.847330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609d9d2ed8cc'
down_revision: Union[str, None] = '4c343cfa2628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
