"""auto_generated_migration

Revision ID: 624ed97e9fe0
Revises: 73a3841e4b98
Create Date: 2025-02-18 12:14:48.118274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624ed97e9fe0'
down_revision: Union[str, None] = '73a3841e4b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'status')
    # ### end Alembic commands ###
