"""add sequence to scenes

Revision ID: a543bb693164
Revises: a543bb693163
Create Date: 2024-02-18 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a543bb693164'
down_revision: Union[str, None] = 'a543bb693163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('sequence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'sequence')
    # ### end Alembic commands ### 